name: "CI"

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2", "3.3"]
        rails: ["6.1", "7.0", "7.1", "7.2"]
        include:
          - ruby: "3.3"
            rails: "main"

    env:
      RAILS_ENV: test
      RAILS_VERSION: "${{ matrix.rails }}"

    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby ${{ matrix.ruby }}
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Run Setup
        run: |
          bin/setup

      - name: Run Tests
        run: |
          bundle exec rake
